/**
 * Lista de atividades com MET — 602 itens, na ordem em que a nutricionista enviou
 * (planilha "tabela_met_dietsystem.xlsx", 01/10/2026). É a lista do Compêndio de
 * Atividades Físicas traduzida para o português; os nomes estão como vieram,
 * inclusive os erros de digitação do original ("fisicullturismo"), para que a
 * busca por um nome conhecido continue achando o mesmo item.
 *
 * Só DADOS. A conta fica em met.mjs. Cada linha: [número, atividade, MET].
 * STATUS: "em vistoria" — conferir amostras contra o Compêndio oficial antes de
 * tratar como definitivo (o MET de cada item é o da planilha, não foi reescrito).
 */
export const ATIVIDADES_MET = [
  [1, "Pular corda, velocidade moderada, geral", 10],
  [2, "Ciclismo, BMX ou montanha", 8.5],
  [3, "Ciclismo, < 16 km/h, geral, lazer, para trabalho ou prazer (cód. 115 de Taylor)", 4],
  [4, "Ciclismo, velocidade em geral", 8],
  [5, "Ciclismo, 16 a 19 km/h, lazer, lento, esforço leve", 6],
  [6, "Ciclismo, 19 a 22 km/h, lazer, esforço moderado", 8],
  [7, "Ciclismo, 22 a 25 km/h, corrida ou lazer, rápido, esforço vigoroso", 10],
  [8, "Ciclismo, 25 a 30 km/h, corrida/sem explosão ou > 30 km/h, explosivo, muito veloz, corrida em geral", 12],
  [9, "Ciclismo, > 32 km/h, corrida, sem explosão", 16],
  [10, "Ciclismo, pedalando monociclo", 5],
  [11, "Ciclismo, estacionário, geral", 7],
  [12, "Ciclismo, estacionário, 50W, esforço muito leve", 3],
  [13, "Ciclismo, estacionário, 100 W, esforço leve", 5.5],
  [14, "Ciclismo, estacionário, 150 W, esforço moderado", 7],
  [15, "Ciclismo, estacionário, 200 W, esforço vigoroso", 10],
  [16, "Ciclismo, estacionário, 250 W, esforço muito vigoroso", 12],
  [17, "Calistenia (i.e., flexões, abdominais, puxadas), pesado, esforço vigoroso", 8],
  [18, "Calistenia, exercício em casa, esforço leve ou moderado, geral (ex: exercícios para as costas), levantar e deitar no chão (cód. 150 de Taylor)", 3.5],
  [19, "Treinamento em circuito, geral", 8],
  [20, "Levantamento de peso (pesos livres, Nautilus ou modulados universais), power-lifting ou fisicullturismo, esforço vigoroso (cód. 210 de Taylor)", 6],
  [21, "Exercícios em centros de saúde (fitness, academias, musculação, etc.), geral (cód. 160 de Taylor)", 5.5],
  [22, "Ergômetros de esteira e escada, geral", 9],
  [23, "Remo, ergômetro estacionário, geral", 7],
  [24, "Remo, estacionário, 50 W, esforço leve", 3.5],
  [25, "Remo, estacionário, 100 W, esforço moderado", 7],
  [26, "Remo, estacionário, 150 W, esforço vigoroso", 8.5],
  [27, "Remo, estacionário, 200 W, esforço muito vigoroso", 12],
  [28, "Ski-Machine (ergômetro de esqui), geral", 7],
  [29, "Slimnastics, jazzercise (atividades ginásticas envolvendo movimento do jazz enquanto dança)", 6],
  [30, "Alongamento, Hatha-Yoga", 2.5],
  [31, "Alongamento leve", 2.5],
  [32, "Conduzir aulas de ginástica aeróbia", 4],
  [33, "Hidroginástica (aeróbia, calistênica/localizada)", 3],
  [34, "Levantamento de pesos (pesos livres, Nautilus ou modulados universais), esforço leve ou moderado, rotina leve, geral", 7],
  [35, "Turbilhão, sentado", 1],
  [36, "Balé ou dança moderna, twist, jazz, sapateado, jitterbug (dança em seis tempos, em pares, caracterizada por rodopios velozes – rockabilly)", 4.8],
  [37, "Dança aeróbia, geral", 6.5],
  [38, "Dança aeróbia, step, com step de 15-20 cm", 8.5],
  [39, "Dança aeróbia, step, com step de 25-30 cm", 10],
  [40, "Dança aeróbia, baixo impacto", 5],
  [41, "Dança aeróbia, alto impacto", 7],
  [42, "Dança Geral, Grega, Oriente Médio, hula, flamenco, swing, dança do ventre", 4.5],
  [43, "Dança de salão, rápido (cód. 125 de Taylor)", 5.5],
  [44, "Dança de salão, rápido (disco, folk, square), line dancing (similar à quadrilha brasileira), dança irlandesa, polka, country", 4.5],
  [45, "Dança de salão, devagar (p.ex., valsa, foxtrot, dança lenta), samba, tango, séc XIX, mambo, chacha", 3],
  [46, "Anishinaabe ou outra dança ameríndia tradicional (danças indígenas em geral)", 5.5],
  [47, "Pesca, geral", 3],
  [48, "Cavando para procurar minhocas, com pá", 4],
  [49, "Pesca em beira de rio, caminhando", 4],
  [50, "Pesca de barco, sentado", 2.5],
  [51, "Pesca de beira de rio, em pé (cód. 660 de Taylor)", 3.5],
  [52, "Pesca em correnteza, com botas de pescador (cód. 670 de Taylor)", 6],
  [53, "Pesca sentado, imóvel", 2],
  [54, "Caça, arco e flecha ou arbalete", 2.5],
  [55, "Caça, cervo, alce, animais silvestres de grande porte (cód. 170 de Taylor)", 6],
  [56, "Caça, pato selvagem, em terreno pantanoso, brejo ou espelho d´água", 2.5],
  [57, "Caça, geral", 5],
  [58, "Caça, faisão ou galo silvestre (cód. 680 de Taylor)", 6],
  [59, "Caça, coelho/lebre, esquilo, aves silvestres, gambá, animais silvestres de pequeno porte (cód. 690 de Taylor)", 5],
  [60, "Tiro de pistola ou tiro ao alvo imóvel, em pé", 2.5],
  [61, "Varrer tapetes, varrer o chão", 3.3],
  [62, "Limpeza, pesada (p.ex., lavar carro, lavar janelas, limpar garagem), esforço vigoroso", 3],
  [63, "Varrer o chão", 3.5],
  [64, "Múltiplas tarefas domésticas todas de uma vez, leve esforço", 2.5],
  [65, "Múltiplas tarefas domésticas todas de uma vez, esforço moderado", 3.5],
  [66, "Múltiplas tarefas domésticas todas de uma vez, esforço vigoroso", 4],
  [67, "Limpeza, casa ou cabana, geral", 3],
  [68, "Limpeza, leve (espanar pó, passar aspirador, mudar roupa de cama, levar lixo para fora)", 2.5],
  [69, "Lavar pratos de pé ou em geral (atividade não dividida em componentes de pé/caminhando)", 2.3],
  [70, "Lavar pratos, tirar os pratos da mesa, caminhar", 2.5],
  [71, "Usar o aspirador de pó", 3.5],
  [72, "Abatendo animais", 6],
  [73, "Cozinhar e preparar comida - de pé, sentado ou em geral (atividade não dividida em componentes de pé/ caminhando)", 2],
  [74, "Servir comida, colocar a mesa - envolvendo caminhar e estar de pé", 2.5],
  [75, "Cozinhar ou preparar comida – caminhando", 2.5],
  [76, "Alimentando animais", 2.5],
  [77, "Descolar provisões (compras de mercado) (carregar/arrumar provisões, fazer compras sem carrinho)", 2.5],
  [78, "Carregar compras escada acima", 7.5],
  [79, "Preparando pão em forno externo (lenha, carvão etc)", 3],
  [80, "Comprar alimentos, com ou sem carrinho de supermercado, em pé ou caminhando", 2.3],
  [81, "Fazer compras, em pé ou caminhando (shopping) (compras, excluídas as de mercado - provisões)", 2.3],
  [82, "Passar a roupa", 2.3],
  [83, "Sentado, costurando, bordando, empacotamento leve (presentes)", 1.5],
  [84, "Lavar roupa de pé, dobrar ou pendurar roupas, colocar roupa no lavador ou secador, fazer malas", 2],
  [85, "Transportar roupas caminhando, juntar roupas para empacotar, separar roupa suja ou limpa", 2.3],
  [86, "Fazer a cama", 2],
  [87, "Fazer xarope, extrair essência (seiva) para fazer açúcar (incluindo carregar baldes, transportar lenha)", 5],
  [88, "Mudar móveis de lugar, faxina", 6],
  [89, "Esfregar o chão, com apoio de mãos e joelhos", 3.8],
  [90, "Varrer garagem, calçada ou fora de casa", 4],
  [91, "De pé, encaixotando/desencaixotando, suspensão ocasional de utensílios domésticos", 3.5],
  [92, "Transportando utensílios domésticos com necessidade de caminhar - esforço moderado", 3],
  [93, "Regando plantas", 2.5],
  [94, "Acendendo a lareira (preparação inclusive)", 2.5],
  [95, "Transportar utensílios domésticos escada acima, carregar caixas ou móveis", 9],
  [96, "De pé, esforço leve (trocar lâmpada etc.)", 2],
  [97, "Caminhar, esforço leve, sem limpar (aprontar-se para sair, fechar portas, janelas etc)", 3],
  [98, "Sentado, brincando com criança (s) – esforço leve (apenas períodos ativos)", 2.5],
  [99, "De pé, brincando com criança (s) – esforço leve (apenas períodos ativos)", 2.8],
  [100, "Caminhar/correr brincando com criança (s) - esforço moderado (apenas períodos ativos)", 4],
  [101, "Caminhar/correr brincando com criança (s) - esforço vigoroso (apenas períodos ativos)", 5],
  [102, "Carregando criança pequena", 3],
  [103, "Cuidar de criança - sentado ou ajoelhado: vesti-la, dar banho, enfeitá-la, alimentá-la, levantá-la ocasionalmente- esforço leve", 2.5],
  [104, "Cuidar de criança - de pé: vesti-la, dar banho, enfeitá-la, alimentá-la, levantá-la ocasionalmente esforço leve", 3],
  [105, "Cuidar de idoso, adulto incapacitado (apenas períodos ativos)", 4],
  [106, "Recostar-se com um bebê no colo", 1.5],
  [107, "Sentado, brincando com animais, esforço leve (apenas períodos ativos)", 2.5],
  [108, "Em pé, brincando com animais, esforço leve (apenas períodos ativos)", 2.8],
  [109, "Caminhar /correr, brincando com animais, esforço leve (apenas períodos ativos)", 2.8],
  [110, "Caminhar/correr, brincando com animais, esforço moderado (apenas períodos ativos)", 4],
  [111, "Caminhar/correr, brincando com animais, esforço vigoroso (apenas períodos ativos)", 5],
  [112, "Em pé, dando banho no cachorro", 3.5],
  [113, "Conserto de carro (pesado, com trabalho corporal)", 4],
  [114, "Conserto de carro (leve, sem trabalho corporal)", 3],
  [115, "Carpintaria, geral, em ateliê (cód. 620 de Taylor)", 3],
  [116, "Carpintaria, exterior da casa, instalar calhas, construir uma cerca (cód. 640 de Taylor)", 6],
  [117, "Carpintaria, acabamento de móveis ou cabines pequenas (closets etc)", 4.5],
  [118, "Carpintaria, serrando madeira dura", 7.5],
  [119, "Calafetagem, cabana de madeira", 5],
  [120, "Calafetagem, exceto cabana de madeira", 4.5],
  [121, "Limpar calhas", 5],
  [122, "Arrumar a garagem (prospectando garagem em desordem)", 5],
  [123, "Instalar janelas pesadas", 5],
  [124, "Colocar ou remover carpete", 4.5],
  [125, "Colocar piso ou linóleo", 4.5],
  [126, "Pintar, exterior da casa (cód. 650 de Taylor)", 5],
  [127, "Pintar, colocar papel de parede, revestir de gesso, raspagem, interior da casa, pendurar placas de pedra, remodelagem", 3],
  [128, "Pintar (cód. 630 de Taylor)", 4.5],
  [129, "Colocar e remover tela de piche em barcos (manta ou calafetagem do barco)", 3],
  [130, "Consertar telhado", 6],
  [131, "Revestir chão com areia com uso de máquina", 4.5],
  [132, "Raspar ou pintar um barco a vela ou motor", 4.5],
  [133, "Retirar terra com pá", 5],
  [134, "Lavar e encerar o casco de barco, carro, barco a motor, aeroplano", 4.5],
  [135, "Lavar e pintar cercas", 4.5],
  [136, "Reparos elétricos (fios etc) e de canos em geral", 3],
  [137, "Ficar deitado e quieto, assistindo televisão", 1],
  [138, "Ficar deitado e quieto, fazendo nada, deitado na cama acordado, escutando música (sem falar ou ler)", 1],
  [139, "Sentado, quieto, vendo TV", 1],
  [140, "Sentado e quieto, fumando, escutando música (sem falar ou ler), assistindo a um filme no cinema", 1],
  [141, "Dormir", 0.9],
  [142, "De pé, quieto (p.ex., esperar numa fila)", 1.2],
  [143, "Reclinado, escrevendo", 1],
  [144, "Reclinado, falando (com terceiros ou ao telefone)", 1],
  [145, "Reclinado, lendo", 1],
  [146, "Meditando", 1],
  [147, "Transportar, carregar ou empilhar lenha, carregar ou descarregar lenha ou pranchas (madeira para construção)", 5],
  [148, "Cortar lenha ou troncos", 6],
  [149, "Limpar o terreno, transportar gravetos", 5],
  [150, "Cavar caixa de areia", 5],
  [151, "Cavar, remover terra, renovar terra do jardim (cód. 590 de Taylor)", 5],
  [152, "Jardinagem com equipamentos pesados, trabalhando o jardim, operando serra elétrica", 6],
  [153, "Espalhar pedra picada (cascalho)", 5],
  [154, "Espalhar cal", 5],
  [155, "Aparar o gramado, geral", 5.5],
  [156, "Aparar gramado, dirigindo um aparador/cortador (cód. 550 de Taylor)", 2.5],
  [157, "Aparar gramado, andando, aparador/cortador manual (cód. 570 de Taylor)", 6],
  [158, "Aparar gramado, andando, aparador/cortador com motor", 5.5],
  [159, "Aparar gramado, cortador com motor (cód. 590 de Taylor)", 4.5],
  [160, "Operar soprador de neve, andando", 4.5],
  [161, "Semear flores e arbustos", 4.5],
  [162, "Plantar árvores", 4.5],
  [163, "Varrer folhas com ancinho", 4.3],
  [164, "Varrer folhas com ancinho (Taylor Code 600)", 4],
  [165, "Varrer o telhado com vassoura de neve", 4],
  [166, "Dirigir soprador de neve", 3],
  [167, "Ensacar grama ou folhas", 4],
  [168, "Cavando, neve, com as mãos (cód. 610 de Taylor)", 6],
  [169, "Aparar arbustos ou árvores, cortador manual", 4.5],
  [170, "Aparar arbustos ou árvores, cortador com motor", 3.5],
  [171, "Andar, aplicar fertilizante ou semear gramado", 2.5],
  [172, "Regar gramado ou jardim, de pé ou andando", 1.5],
  [173, "Retirar erva daninha, cultivar jardim (cód. 580 de Taylor)", 4.5],
  [174, "Jardinagem, geral", 4],
  [175, "Pegar frutas de árvores, pegar frutas ou vegetais, esforço moderado", 3],
  [176, "Recolher/colher folhas, gravetos ou vegetais, andando ou em pé", 3],
  [177, "Caminhando, juntando as ferramentas de jardinagem", 3],
  [178, "Sentado, jogando cartas ou jogos de mesa", 1.5],
  [179, "De pé, desenhando (escrevendo), jogando em cassinos, operando máquinas copiadoras", 2.3],
  [180, "Sentado, lendo, livro, jornal etc.", 1.3],
  [181, "Sentado, escrevendo, trabalho de escritório", 1.8],
  [182, "De pé, conversando ou falando ao telefone", 1.8],
  [183, "Sentado, conversando ou falando ao telefone", 1.5],
  [184, "Sentado, estudando, geral, incluindo ler e/ou escrever", 1.8],
  [185, "Sentado em sala de aula, geral, incluindo tomar notar e discussões em classe", 1.8],
  [186, "De pé, lendo", 1.8],
  [187, "Em pé, miscelânea", 2],
  [188, "Sentado, artes e artesanatos, esforço leve", 1.5],
  [189, "Sentado, artes e artesanatos, esforço moderado", 2],
  [190, "Em pé, artes e artesanatos, esforço leve", 1.8],
  [191, "Em pé, artes e artesanatos, esforço moderado", 3],
  [192, "Em pé, artes e artesanatos, esforço vigoroso", 3.5],
  [193, "Retiro/reunião familiar envolvendo atividades sentado, relaxando, falando e comendo", 1.5],
  [194, "Fazer viagem, viajar/ férias envolvendo caminhadas e andar a cavalo", 2],
  [195, "Acampar envolvendo atividades em pé, sentando, andando, esforço de leve a moderado", 2.5],
  [196, "Sentado em evento desportivo, como espectador", 1.5],
  [197, "Violoncelo", 2],
  [198, "Regência", 2.5],
  [199, "Bateria", 4],
  [200, "Flauta (sentado)", 2],
  [201, "Corneta", 2],
  [202, "Piano ou órgão", 2.5],
  [203, "Trombone", 3.5],
  [204, "Trompete", 2.5],
  [205, "Violino", 2.5],
  [206, "Instrumentos de sopro de madeira de forma geral", 2],
  [207, "Violão/guitarra, clássico, folk (sentado)", 2],
  [208, "Guitarra, banda de rock and roll (em pé)", 3],
  [209, "Fanfarra, tocando instrumento, rodando bastão (andando)", 4],
  [210, "Fanfarra, percussão (andando)", 3.5],
  [211, "Confeitaria, geral, esforço moderado", 4],
  [212, "Confeitaria, esforço leve", 2.5],
  [213, "Encardernação de livros", 2.3],
  [214, "Construção de estradas (incluindo recolhimento de entulho, direção de máquinas pesadas)", 6],
  [215, "Construção de estradas, controlando o tráfico (em pé)", 2],
  [216, "Carpintaria, geral", 3.5],
  [217, "Transporte de cargas pesadas, como tijolos", 8],
  [218, "Transporte de cargas moderadas subindo escadas, mover caixas (7 a 18 kg)", 8],
  [219, "Camareira, fazendo a cama (enfermeiras inclusive)", 2.5],
  [220, "Mineração de carvão, prospectando", 6.5],
  [221, "Mineração de carvão, erigindo suportes", 6.5],
  [222, "Mineração de carvão, geral", 6],
  [223, "Mineração de carvão, peneirando", 7],
  [224, "Construção civil, a céu aberto, remodelagem", 5.5],
  [225, "Manutenção – encerando o chão com enceradeira", 3],
  [226, "Manutenção – limpando pia e banheiro, esforço leve", 2.5],
  [227, "Manutenção – tirando o pó, esforço leve", 2.5],
  [228, "Manutenção – cobrindo/limpando piso de ginásio (arena), esforço moderado", 4],
  [229, "Manutenção – limpeza geral, esforço moderado", 3.5],
  [230, "Manutenção – varrendo, esforço moderado", 3.5],
  [231, "Manutenção – levar o lixo para fora, esforço moderado", 3],
  [232, "Manutenção – utilizar aspirador de pó, esforço leve", 2.5],
  [233, "Manutenção – utilizar aspirador de pó, esforço moderado", 3],
  [234, "Eletricista, bombeiro hidráulico", 3.5],
  [235, "Atividade na fazenda, empilhando feno, varrendo cocheiras, limpando granjas, criação de aves, esforço vigoroso", 8],
  [236, "Atividade na fazenda, conduzindo gado, não extenuante (andando), esforço moderado", 3.5],
  [237, "Atividade na fazenda, conduzindo gado ou outro rebanho sobre cavalo, esforço moderado", 4],
  [238, "Atividade na fazenda, conduzindo gado ou outro rebanho, dirigindo, esforço leve", 2],
  [239, "Atividade na fazenda, dirigindo colheitadeira, cortando feno, trabalho de irrigação", 2.5],
  [240, "Atividade na fazenda, dirigindo trator", 2.5],
  [241, "Atividade na fazenda, alimentando pequenos animais", 4],
  [242, "Atividade na fazenda, alimentando gado, cavalos", 4.5],
  [243, "Atividade na fazenda, transportando água para animais, transportando água em geral", 4.5],
  [244, "Atividade na fazenda, cuidando dos animais (escovando, tosando, ajudando no parto, cuidados médicos, marcando)", 6],
  [245, "Atividade na fazenda, recolhendo feixes de palha/feno com ancinho/garfo, limpando currais e cocheiras, esforço vigoroso", 8],
  [246, "Atividade na fazenda, ordenha manual, esforço moderado", 3],
  [247, "Atividade na fazenda, ordenha mecânica, esforço leve", 1.5],
  [248, "Atividade na fazenda, recolhendo grãos com pá, esforço moderado 4", 4],
  [249, "Bombeiro (soldado do fogo), geral", 12],
  [250, "Bombeiro, subindo escadas aceleradamente", 11],
  [251, "Bombeiro, transportando mangueiras no chão", 8],
  [252, "Atividade florestal, cortando com machado, acelerado", 17],
  [253, "Atividade florestal, cortando com machado, lentamente", 5],
  [254, "Atividade florestal, raspando árvores", 7],
  [255, "Atividade florestal, carregando troncos", 11],
  [256, "Atividade florestal, derrubando árvores", 8],
  [257, "Atividade florestal, geral", 8],
  [258, "Atividade florestal, semeando", 4],
  [259, "Atividade florestal, plantando manualmente", 6],
  [260, "Atividade florestal, serrando manualmente", 7],
  [261, "Atividade florestal, serrando, motor", 4.5],
  [262, "Atividade florestal, cortando árvores em pedaços", 9],
  [263, "Trabalho com peles de animais (peleteiro)", 4.5],
  [264, "Cuidar de cavalos", 6],
  [265, "Equitação, galope", 8],
  [266, "Equitação, trote", 6.5],
  [267, "Equitação, ao passo lento", 2.6],
  [268, "Serralheria", 3.5],
  [269, "Operando máquinas, trabalhando lâminas de metal", 2.5],
  [270, "Operando máquinas, operando grua", 3],
  [271, "Operando máquinas, operando perfuradora ou britadeira", 5],
  [272, "Operando máquinas, martelar levemente, usar furadeira", 4],
  [273, "Operando máquinas, soldando", 3],
  [274, "Maçonaria, concreto", 7],
  [275, "Fazer massagem, em pé", 4],
  [276, "Mover, empurrar objetos pesados, 34 kg ou mais (mobiliário, mudanças)", 7.5],
  [277, "Mergulho (skindiving ou Scuba diving) como homem-rã (marinha)", 12],
  [278, "Operar equipamento pesado/automatizado, estacionário, sem conduzi-lo/dirigi-lo", 2.5],
  [279, "Trabalho em plantação de laranjas", 4.5],
  [280, "Trabalho de impressão gráfica (em pé)", 2.3],
  [281, "Policial, controlador de tráfego (em pé)", 2.5],
  [282, "Policial, dirigindo viatura (sentado)", 2],
  [283, "Policial, viajando em viatura (sentado)", 1.3],
  [284, "Policial, fazendo uma prisão (em pé)", 4],
  [285, "Reparo de sapatos, geral", 2.5],
  [286, "Cavando com pá, cavando fossas", 8.5],
  [287, "Cavando com pá, pesado (mais de 7kg/min)", 9],
  [288, "Cavando com pá, leve (menos de 4,5 kg/min)", 6],
  [289, "Cavando com pá, moderado (4,5 a 7 kg/min)", 7],
  [290, "Sentado, trabalho leve de escritório, geral (laboratório, reparo de relógios ou computadores, manuseio de ferramentas leves), lendo ou dirigindo", 1.5],
  [291, "Sentado, encontros e congressos, geral, falando ou não, comendo em encontro de trabalho", 1.5],
  [292, "Sentado, moderado (acionar alavancas pesadas, manejar cortador de grama ou forcado, operar guindaste), dando aulas de alongamento ou ioga", 2.5],
  [293, "Em pé, leve (atendimento em bar, vendas, operando copiadoras, armando árvore de Natal), em pé e falando no trabalho, mudando de roupa em aulas de educação física", 2.3],
  [294, "Em pé, leve/moderado (trabalhos manuais pesados, soldagem, guardar compras na despensa, reparo de carros, empacotar caixas para mudança etc.), cuidar de pacientes (como em atividades de enfermagem)", 3],
  [295, "Erguendo pesos continuamente (4-9 kg), com períodos curtos de caminhada ou repouso", 4],
  [296, "De pé, moderado (trabalhos manuais feitos aceleradamente, levantar pesos de 22 kg, atrelar animais ou trançar cordas", 3.5],
  [297, "De pé, moderado/ pesado (levantar pesos > 22 kg, maçonaria, pintura, colocar papel de parede)", 4],
  [298, "Siderurgia/Metalurgia, alisar o aço 5.5", 5.5],
  [299, "Siderurgia/Metalurgia, forjar peças", 5.5],
  [300, "Siderurgia/Metalurgia, laminação", 8],
  [301, "Siderurgia/Metalurgia, fresagem", 8],
  [302, "Siderurgia/Metalurgia, remover entulho metálico", 11],
  [303, "Siderurgia/Metalurgia, fornalha", 7.5],
  [304, "Siderurgia/Metalurgia, entornar aço nas formas", 5.5],
  [305, "Siderurgia/Metalurgia, trabalhos em geral", 8],
  [306, "Alfaiataria, corte", 2.5],
  [307, "Alfaiataria, em geral", 2.5],
  [308, "Alfaiataria, costura a mão", 2],
  [309, "Alfaiataria, costura a máquina", 2.5],
  [310, "Alfaiataria, passar a ferro", 4],
  [311, "Alfaiataria, tecelagem", 3.5],
  [312, "Dirigir caminhão, carregar e descarregar caminhão (de pé)", 6.5],
  [313, "Digitação em máquina elétrica, manual ou computador", 1.5],
  [314, "Usar ferramentas pesadas, como ferramentas pneumáticas (macaco, arado,etc)", 6],
  [315, "Usar ferramentas manuais e pesadas como pá de ferro, picareta, pá", 8],
  [316, "Caminhar no trabalho (no escritório ou área de trabalho), a menos de 3 km/h e bem devagar", 1.2],
  [317, "Caminhar no trabalho (no escritório), 5 km/h, velocidade moderada, sem carregar nada", 3.3],
  [318, "Caminhar no trabalho (no escritório), 5 a 6 km/h, velocidade rápida, sem carregar nada", 3.8],
  [319, "Caminhar, 4 km/h, lentamente, carregando objetos leves com menos de 11 kg", 3],
  [320, "Andando, juntando coisas no trabalho, pronto para sair", 3],
  [321, "Caminhar, 5 km/h, velocidade moderada, carregando objetos leves com menos de 11 kg", 4],
  [322, "Caminhando, empurrando uma cadeira de rodas", 4],
  [323, "Caminhar, 5 a 6 km/h, rapidamente, carregando objetos de menos de 11 kg", 4.5],
  [324, "Caminhar, descer rampas ou escadas, ficar de pé, carregando objetos variando de 11 a 22 kg", 5],
  [325, "Caminhar, descer escadas ou rampas, ficar de pé, carregando objetos variando de 22 a 34 kg", 6.5],
  [326, "Caminhar, descer escadas ou rampas, ficar de pé, carregando objetos variando de 34 a 45 kg", 7.5],
  [327, "Caminhar, descer escadas ou rampas, ficar de pé, carregando objetos de 45 kg ou mais", 8.5],
  [328, "Trabalhar em cenário de teatro, como ator ou nos bastidores", 3],
  [329, "Ensinar Educação Física, exercícios, aulas esportivas, sem jogos esportivos", 4],
  [330, "Ensinar Educação Física, exercícios, aulas esportivas (participando da aula)", 6.5],
  [331, "Combinação de caminhada e atividades laborais (componente laboral com menos de 10 minutos) (Cód. 180 de Taylor)", 6],
  [332, "Jogging em geral", 7],
  [333, "Jogging, estacionário", 8],
  [334, "Jogging em uma mini-excursão", 4.5],
  [335, "Correr, 8 km/h (7,5 min.km-1)", 8],
  [336, "Correr, 8,3 km/h (7,1 min.km-1)", 9],
  [337, "Correr, 9,7 km/h (6,2 min.km-1)", 10],
  [338, "Correr, 10,7 km/h (5,6 min.km-1)", 11],
  [339, "Correr, 11,2 km/h (5,3 min.km-1)", 11.5],
  [340, "Correr, 12,0 km/h (5 min.km-1)", 12.5],
  [341, "Correr, 12,8 km/h (4,6 min.km-1)", 13.5],
  [342, "Correr, 13,8 km/h (4,3 min.km-1)", 14],
  [343, "Correr, 14,4 km/h (4,0 min.km-1)", 15],
  [344, "Correr, 16,0 km/h (3,7 min.km-1)", 16],
  [345, "Correr, 17,5 km/h (3,4 min.km-1)", 18],
  [346, "Correr, terrenos irregulares, tipo cross-country", 9],
  [347, "Correr (Cód. 200 de Taylor)", 8],
  [348, "Correr, subir rampa ou escada", 1.5],
  [349, "Correr numa pista, treino de equipe", 10],
  [350, "Correr, treinamento, empurrar cadeira de roda em situação competitiva", 8],
  [351, "De pé, se aprontar para ir dormir, em geral", 2],
  [352, "Sentado na privada (vaso sanitário)", 1],
  [353, "Tomar banho (sentado)", 1.5],
  [354, "Vestir-se ou tirar a roupa (de pé ou sentado)", 2],
  [355, "Comer (sentado)", 1.5],
  [356, "Conversar e comer ao mesmo tempo ou somente comer (de pé)", 2],
  [357, "Tomar remédio, sentado ou em pé", 1],
  [358, "Cuidar-se, sentado ou de pé (lavar-se, barbear-se, escovar os dentes, urinar, lavar as mãos, maquiar-se)", 2],
  [359, "Fazer um penteado", 2.5],
  [360, "Ter o cabelo ou unha cuidados por terceiros, sentado", 1],
  [361, "Tomar banho de chuveiro, secar-se (de pé)", 2],
  [362, "Atividade Sexual Ativa, esforço vigoroso", 1.5],
  [363, "Atividade Sexual Geral, esforço moderado", 1.3],
  [364, "Atividade Sexual Passiva, esforço leve, beijos, abraços", 1],
  [365, "Arco e flecha (sem finalidade de caça)", 3.5],
  [366, "Badminton, competitivo (Cód. 450 de Taylor)", 7],
  [367, "Badminton, não competitivo, simples e duplas, geral", 4.5],
  [368, "Basquetebol, jogo (Cód. 490 de Taylor)", 8],
  [369, "Basquetebol, sem ser jogo, em geral (Cód. 480 de Taylor)", 6],
  [370, "Basquetebol, oficial (Cód. 500 de Taylor)", 7],
  [371, "Basquetebol, arremessar a cesta", 4.5],
  [372, "Basquetebol, em cadeiras de roda", 6.5],
  [373, "Bilhar", 2.5],
  [374, "Boliche (Cód. 390 de Taylor)", 3],
  [375, "Boxe, no ringue, em geral", 12],
  [376, "Boxe, punching bag", 6],
  [377, "Boxe, sparring (lutador auxiliar, que atua como adversário para treinamento de golpes)", 9],
  [378, "Broomball (jogo similar ao hóquei, com bola de borracha no lugar do disco, uma espécie de vassoura no lugar do taco e no qual os jogadores correm sobre o gelo com auxílio de sapatos especiais)", 7],
  [379, "Jogos de criança com movimentação corporal intensa (amarelinha, 4-quadros, queimado, brinquedos de playgroud, taco etc)", 5],
  [380, "Treinar: futebol americano, futebol, basquetebol, basebol, natação, etc", 4],
  [381, "Cricket (rebater, lançar)", 5],
  [382, "Croquet", 2.5],
  [383, "Curling (desporto de equipe praticado sobre o gelo, no qual se busca impulsionar rochas de 19 kg na direção de um alvo de 3,6 m de diâmetro)", 4],
  [384, "Dardo, na parede ou gramado", 2.5],
  [385, "Corrida de carreta, empurrar ou dirigir carros", 6],
  [386, "Esgrima", 6],
  [387, "Futebol americano, competitivo", 9],
  [388, "Futebol americano, geral (Cód. 510 de Taylor)", 8],
  [389, "Futebol americano ou beisebol, arremesso e pegada", 2.5],
  [390, "Frisbee, em geral", 3],
  [391, "Frisbee, ‘radical’", 8],
  [392, "Golfe, geral", 4.5],
  [393, "Golfe, caminhando e transportando tacos", 4.5],
  [394, "Golfe, miniatura", 3],
  [395, "Golfe, caminhando e empurrando tacos", 4.3],
  [396, "Golfe, usando carrinhos elétricos (trollers) (Cód. 070 de Taylor)", 3.5],
  [397, "Ginástica, geral", 4],
  [398, "Hacky sack (Jogo em que deve ser controlada uma pequena massa esférica sem uso das mãos – semelhante a fazer ‘embaixadas’)", 4],
  [399, "Andebol, geral (Cód. 520 de Taylor)", 12],
  [400, "Andebol, meia-quadra", 8],
  [401, "Praticar vôo livre (asa delta)", 3.5],
  [402, "Hóquei, de campo", 8],
  [403, "Hóquei, no gelo", 8],
  [404, "Cavalgar, geral", 4],
  [405, "Cavalgar, selar e cuidas de cavalo", 3.5],
  [406, "Cavalgar, trotar", 6.5],
  [407, "Cavalgar, passeando", 2.5],
  [408, "Colocar ferradura em cavalo", 3],
  [409, "Jai alai (jogo de equipe em que uma bola é lançada com uso de luvas contra paredes em alta velocidade)", 12],
  [410, "Judô, Jiu-jitsu, karatê, kick boxing, tae-kwon-do", 10],
  [411, "Malabarismo (com as mãos, lançando objetos para cima e recuperando-os)", 4],
  [412, "Kickball", 7],
  [413, "Lacrosse (jogo de equipe em que se utilizam bastões (crosse) com redes para arremessar bolas para marcar gols – combina, de certa forma, futebol, basquetebol e hóquei)", 8],
  [414, "Moto-cross", 4],
  [415, "Orienteering (corrida de orientação), trilhas", 9],
  [416, "Paddleball, competitivo (jogo indoor, similar ao squash, com raquetes sem acordoamento, inteiriças)", 10],
  [417, "Paddleball, casual, em geral (Cód. 460 de Taylor)", 6],
  [418, "Pólo", 8],
  [419, "Racketball (jogo semelhante ao tênis, com raquetes maiores e quadra menor), competitivo", 10],
  [420, "Racketball, casual, geral (Cód. 470 de Taylor)", 7],
  [421, "Escalar ou subir rochas", 1.1],
  [422, "Escalar em rochas, rappel", 8],
  [423, "Pular corda, velocidade rápida", 12],
  [424, "Pular corda, velocidade lenta", 8],
  [425, "Rugby", 10],
  [426, "Shuffleboard (jogo em que se impulsionam discos, em contato com o solo, com uso de tacos), boliche em gramado", 3],
  [427, "Andar de skate", 5],
  [428, "Patinação (Cód. 360 de Taylor)", 7],
  [429, "Roller blanding (in-line skating) (patinação com uso de patins com rolamentos em linha)", 12.5],
  [430, "Saltar de pára-quedas", 3.5],
  [431, "Futebol competitivo", 10],
  [432, "Futebol casual, geral (Cód. 540 de Taylor)", 7],
  [433, "Softball ou beisebol, velocidade rápida ou lenta, geral (Cód. 440 de Taylor)", 5],
  [434, "Softball, oficial (adaptação do beisebol, com uso de uma bola maior)", 4],
  [435, "Softball, lançamentos", 6],
  [436, "Squash (Cód. 530 de Taylor)", 12],
  [437, "Tênis de mesa, pingue-pongue (Cód. 410 de Taylor)", 4],
  [438, "Tai chi chuan", 4],
  [439, "Tênis, geral", 7],
  [440, "Tênis, duplas (Cód. 430 de Taylor)", 6],
  [441, "Tênis, duplas", 5],
  [442, "Tênis, simples (Cód. 420 de Taylor)", 8],
  [443, "Trampolim", 3.5],
  [444, "Voleibol (Cód. 400 de Taylor)", 4],
  [445, "Voleibol, competitivo, em ginásio", 1.8],
  [446, "Voleibol, não-competitivo, com 6 a 9 membros no time, geral", 3],
  [447, "Voleibol de praia", 8],
  [448, "Luta romana (1 match = 5 minutos)", 6],
  [449, "Wallyball, geral (variação do volibol, jogado em quadra de racquetball fechada – 12 x 6 m – em que a bola toca as paredes - walls)", 1.7],
  [450, "Atletismo (peso, disco, martelo)", 4],
  [451, "Atletismo (salto em altura, distância e triplo, dardo, salto com vara)", 6],
  [452, "Atletismo (obstáculos - steeplechase, barreiras)", 10],
  [453, "Dirigir carro ou caminhão leve", 2],
  [454, "Dirigir carro ou caminhão", 1],
  [455, "Dirigir um ônibus", 1],
  [456, "Pilotar avião", 2],
  [457, "Dirigir patinete motorizado ou motocicleta", 2.5],
  [458, "Conduzir avião para fora do hangar", 6],
  [459, "Dirigir caminhão pesado, trator ou ônibus", 3],
  [460, "Carregar mochila de viagem (backpacking ou, na gíria brasileira ‘mochileiro’) (Cód. 050 de Taylor)", 7],
  [461, "Carregar criança ou carga de aproximadamente 7 kg (maleta), terreno plano ou em descidas", 3.5],
  [462, "Carregar carga em subidas, geral", 9],
  [463, "Carregar carga entre 0,5 e 7 kg, em subidas", 5],
  [464, "Carregar carga entre 7 e 11 kg, em subidas", 6],
  [465, "Carregar carga entre 11 e 22 kg, em subidas", 8],
  [466, "Carregar carga entre 22 e 34 kg, em subidas", 10],
  [467, "Carregar carga > de 34 kg, em subidas", 1.2],
  [468, "Carregando ou descarregando o carro", 3],
  [469, "Subir encostas com carga até 4 kg", 7],
  [470, "Subir encostas com carga entre 4 e 10 kg", 7.5],
  [471, "Subir encostas com carga entre 10 e 19 kg", 8],
  [472, "Subir encostas com carga > de 19 kg", 9],
  [473, "Descer encostas/escadas", 3],
  [474, "Caminhadas longas em trilhas ou florestas (Cód. 040 de Taylor)", 6],
  [475, "Observar pássaros como hobby (‘bird watching’)", 2.5],
  [476, "Marchar, de forma marcial e rapidamente", 6.5],
  [477, "Empurrar ou puxar carrinho de bebê com criança", 2.5],
  [478, "Empurrando a cadeira de rodas, em contexto não-ocupacional", 4],
  [479, "Race walking (conteste ou disputa de quem consegue andar o mais rápido possível, quase correndo)", 6.5],
  [480, "Escalar rochas ou montanhas (Cód. 060 de Taylor)", 8],
  [481, "Subir escadas, usando ou subindo uma escada de mão (Cód. 030 de Taylor)", 8],
  [482, "Caminhar usando muletas ou bengalas", 5],
  [483, "Caminhar, andar em casa", 2],
  [484, "Caminhar, menos 3 km/h, de modo confortável, em terreno plano, bem devagar", 2],
  [485, "Caminhar a 3km/h, terreno plano e firme, ritmo lento", 2.5],
  [486, "Caminhar por prazer (Cód. 010 de Taylor)", 3.5],
  [487, "Caminhar da casa para o carro ou ônibus, do carro ou ônibus para outros lugares, como o trabalho", 2.5],
  [488, "Caminhar até a casa de vizinhos ou familiares por razões sociais", 2.5],
  [489, "Caminhar com o cachorro", 3],
  [490, "Caminhar, 4 km/h, superfície firme", 3],
  [491, "Caminhar, 4 km/h, descendo encosta", 2.8],
  [492, "Caminhar, 5 km/h, terreno plano, superfície firme, ritmo moderado", 3.3],
  [493, "Caminhar, 5,5 km/h, terreno plano, superfície firme, caminhando para exercitar-se, ritmo rápido", 3.8],
  [494, "Caminhar, 5,5 km/h, subindo encosta", 6],
  [495, "Caminhar, 6,5 km/h, terreno plano, superfície firme, ritmo muito rápido", 5],
  [496, "Caminhar, 7 km/h, terreno plano, superfície firme, ritmo extremamente rápido", 6.3],
  [497, "Caminhar, 7,5 km/h", 8],
  [498, "Caminhar, por prazer, no intervalo do trabalho", 3.5],
  [499, "Caminhar em pista ou terreno gramado", 5],
  [500, "Caminhar para o trabalho ou aula (Cód. 015 de Taylor)", 4],
  [501, "Caminhar para e de um local externo à casa", 2.5],
  [502, "Conduzir barco a motor", 2.5],
  [503, "Canoagem, em viagem de acampamento (Cód. 270 de Taylor)", 4],
  [504, "Canoagem, colheita manual de arroz selvagem (manuseio da canoa e extrair/bater o grão do caule – regiões pantanosas dos EUA e Canadá)", 3.3],
  [505, "Canoagem, em lago ou mar", 7],
  [506, "Canoagem, remando entre 3 e 6 km/h, esforço leve", 3],
  [507, "Canoagem, remando entre 6 e 9,5 km/h, esforço moderado", 7],
  [508, "Canoagem, remando > de 9,5 km/h, esforço vigoroso", 12],
  [509, "Canoagem, remando por prazer, geral (Cód. 250 de Taylor)", 3.5],
  [510, "Canoagem, remando em competição, em equipe ou duplas (Cód. 260 de Taylor)", 1.2],
  [511, "Mergulhar, da costa ou de plataforma", 3],
  [512, "Remar em caiaque", 5],
  [513, "Conduzir barco a pedal (‘pedalinho’)", 4],
  [514, "Velejar, windsurf, velejar no gelo, geral (Cód. 235 de Taylor)", 3],
  [515, "Velejar, em competição", 5],
  [516, "Velejar (categorias: sunfish, laser, hobby cat), keel boats), velejar em oceano, iatismo", 3],
  [517, "Esqui aquático (Cód. 220 de Taylor)", 6],
  [518, "Skimobiling (atividade semelhante ao snowmobiling – ver descrição no código 19200)", 7],
  [519, "Merguho (Skindiving), rápido", 16],
  [520, "Mergulho (Skindiving), moderado", 12.5],
  [521, "Merguho (Skindiving), scuba diving (com garrafa), geral (Cód. 310 de Taylor)", 7],
  [522, "Mergulhar com snorckel (Cód. 320 de Taylor) (mergulho sem garrafas, em apnéia)", 5],
  [523, "Surfe ou bodyboard", 3],
  [524, "Nadar, estilo livre, em velocidade rápida, esforço vigoroso", 10],
  [525, "Nadar, estilo livre, em velocidade lenta, esforço leve a moderado", 7],
  [526, "Nadar, costas, geral", 7],
  [527, "Nadar, peito, geral", 10],
  [528, "Nadar, borboleta, geral", 11],
  [529, "Nadar, crawl, velocidade rápida (70 m/min), esforço vigoroso", 11],
  [530, "Nadar, crawl, velocidade lenta (45-46 m/min), esforço leve a moderado", 8],
  [531, "Nadar, em lago, oceano ou rio (Cód. 280 e 295 de Taylor)", 6],
  [532, "Nadar por lazer, sem viradas, geral", 6],
  [533, "Nadar, nado lateral, geral", 8],
  [534, "Nado sincronizado", 8],
  [535, "Nadar, andar na água, velocidade rápida, esforço vigoroso", 10],
  [536, "Nadar, andar na água, esforço moderado, geral", 4],
  [537, "Atividades aeróbias na água, calistenia aquática (hidroginástica)", 4],
  [538, "Pólo aquático", 10],
  [539, "Voleibol na água", 3],
  [540, "Jogging na água", 8],
  [541, "Whitewater (descer correntezas em balsas), rafting, andar de caiaque ou canoagem", 5],
  [542, "Remover o gelo da casa (cobrir buracos)", 6],
  [543, "Patinar no gelo, a 14,5 km/h ou menos", 5.5],
  [544, "Patinar no gelo, geral (Cód. 360 de Taylor)", 7],
  [545, "Patinar no gelo, em velocidade rápida (> de 14,5 km/h)", 9],
  [546, "Patinação, veloz, competitiva", 15],
  [547, "Saltar com esquis e subir montanhas carregando os esquis", 7],
  [548, "Esquiar, geral", 7],
  [549, "Esquiar, esqui de fundo (cross-country), velocidade de 4,0 km/h devagar ou com esforço leve, andar esquiando", 7],
  [550, "Esquiar, esqui de fundo (cross-country), velocidade entre 6,5 e 8 km/h velocidade e esforço moderado, geral", 8],
  [551, "Esquiar, esqui de fundo (cross-country), velocidade entre 8,0 e 13 km/h, com velocidade rápida, esforço vigoroso", 9],
  [552, "Esquiar, esqui de fundo (cross-country), velocidade > de 13 km/h, velocidade rápida, corrida (situação competitiva)", 14],
  [553, "Esquiar, esqui de fundo (cross-country), em neve pesada, subindo encostas, esforço máximo, montanhismo de neve", 16.5],
  [554, "Esquiar, descendo encosta, esforço leve", 5],
  [555, "Esquiar, descendo encosta, esforço moderado, geral", 6],
  [556, "Esquiar, descendo encosta em velocidade, esforço vigoroso", 8],
  [557, "Sledding (plataforma onde corredores se movem rapidamente no gelo), descer de tobogã no gelo, bobsledding (plataforma com freio e motor e com dois corredores), andar de trenó (luge) (Cód. 370 de Taylor)", 7],
  [558, "Snow shoeing (andar no gelo com botas especiais, sem afundar no mesmo)", 8],
  [559, "Snowmobiling (conduzir veículo motorizado, adaptado para dslocar-se na superfície da neve)", 3.5],
  [560, "Sentado na igreja, durante a missa, assistindo a uma cerimônia, sentado quieto", 1],
  [561, "Sentado, tocando algum instrumento na igreja", 2.5],
  [562, "Sentado na igreja, falando ou cantando, assistindo a uma cerimônia, sentado, participação ativa", 1.5],
  [563, "Sentado, lendo textos religiosos em casa", 1.3],
  [564, "Em pé na igreja (quieto), assistindo a uma cerimônia", 1.2],
  [565, "Em pé e cantando na igreja, assistindo a uma cerimônia, participação ativa", 2],
  [566, "Ajoelhado na igreja ou em casa, rezando (orando)", 1],
  [567, "Em pé, falando na igreja", 1.8],
  [568, "Caminhando na igreja", 2],
  [569, "Caminhando menos do que 3km/h, muito lento", 2],
  [570, "Caminhando a 4,5 km/h, velocidade moderada, sem carregar nada", 3.3],
  [571, "Caminhando a 5,5 km/h, velocidade rápida, sem carregar nada", 3.8],
  [572, "Caminhar ou ficar em pé, para finalidades religiosas, guia", 2],
  [573, "Orar com dança ou deslocamentos rápidos, danças religiosas na igreja (spirirual dancing)", 5],
  [574, "Servindo comida na igreja", 2.5],
  [575, "Preparando comida na igreja", 2],
  [576, "Lavando pratos / limpando a cozinha da igreja", 2.3],
  [577, "Comendo na igreja", 1.5],
  [578, "Comendo/falando na igreja ou comendo em pé (quermesses)", 2],
  [579, "Limpando a igreja", 3],
  [580, "Trabalho geral no jardim/pátio da igreja", 5],
  [581, "Em pé, moderado (erguendo 20 kg, juntando peças em ritmo rápido)", 2.5],
  [582, "Em pé, trabalho moderado-pesado", 4],
  [583, "Datilografando, máquina elétrica, manual ou computador", 1.5],
  [584, "Sentado – encontros, geral, com ou sem conversação envolvida", 1.5],
  [585, "Sentado – trabalho leve de escritório, geral", 1.5],
  [586, "Sentado – trabalho moderado", 2.5],
  [587, "Em pé – trabalho leve (falando, preenchendo, montando peças)", 2.3],
  [588, "Sentado, cuidando de crianças (apenas períodos ativos)", 2.5],
  [589, "Em pé, cuidando de crianças (apenas períodos ativos)", 3],
  [590, "Caminhar/correr brincando com crianças, moderado (apenas períodos ativos)", 4],
  [591, "Caminhar/correr brincando com crianças, vigoroso (apenas períodos ativos)", 5],
  [592, "Em pé – trabalho leve/moderado (empacotar, montar/reparar, montar cadeiras e móveis em geral)", 3],
  [593, "Em pé – trabalho moderado (erguer 20 kg, montando peças em ritmo rápido)", 3.5],
  [594, "Em pé – trabalho moderado a pesado", 4],
  [595, "Digitando/datilografando, máquina elétrica, manual ou computador", 1.5],
  [596, "Andando, menos de 3 km/h, bem devagar", 2],
  [597, "Andando, 5 km/h, velocidade moderada, sem carregar nada", 3.3],
  [598, "Andando, 5,5 km/h, velocidade rápida, sem carregar nada", 3.8],
  [599, "Andando, 4 km/h, lentamente e carregando objetos com menos de 10 kg", 3],
  [600, "Andando, 5 km/h, moderadamente e carregando objetos com menos de 10 kg, empurrando algo", 4],
  [601, "Andando, 5,5 km/h, rapidamente e carregando objetos com menos de 10 kg", 4.5],
  [602, "Combinação de atividades andando ou em pé, com finalidade de trabalho voluntário", 3],
];
